<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ca_ES" sourcelanguage="en">
<context>
    <name>SyncPeerDialog</name>
    <message>
        <location filename="../peers_dialog.py" line="81"/>
        <source>Manage connected peers</source>
        <translation type="obsolete">Gestiona peers connectats</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="83"/>
        <source>Discover peers</source>
        <translation type="obsolete">Descobreix peers</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="85"/>
        <source>Manually add a peer</source>
        <translation type="obsolete">Afegeix manualment un peer</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="87"/>
        <source>Remove selected peer</source>
        <translation type="obsolete">Suprimeix el peer seleccionat</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="89"/>
        <source>Remove all peers</source>
        <translation type="obsolete">Suprimeix tots els peers</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="93"/>
        <source>Address</source>
        <translation type="obsolete">Adreces</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="93"/>
        <source>Peer IP</source>
        <translation type="obsolete">IP del peer</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="105"/>
        <source>Error</source>
        <translation type="obsolete">Error</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="105"/>
        <source>Already connected</source>
        <translation type="obsolete">Ja està connectat</translation>
    </message>
    <message>
        <location filename="../peers_dialog.py" line="116"/>
        <source>Cannot add peer</source>
        <translation type="obsolete">No es pot afegir el peer</translation>
    </message>
</context>
<context>
    <name>Synchronizer</name>
    <message>
        <location filename="../../../plugins/synchronizer/synchronizer.py" line="44"/>
        <source>Synchronization</source>
        <translation>Sincronització</translation>
    </message>
    <message>
        <location filename="../../../plugins/synchronizer/synchronizer.py" line="48"/>
        <source>Manage connected peers</source>
        <translation>Gestiona peers connectats</translation>
    </message>
    <message>
        <location filename="../../../plugins/synchronizer/synchronizer.py" line="54"/>
        <source>Show your IP</source>
        <translation>Mostra la seva IP</translation>
    </message>
    <message>
        <location filename="../../../plugins/synchronizer/synchronizer.py" line="79"/>
        <source>Your IP is: {}</source>
        <translation>La teva IP es: {}</translation>
    </message>
    <message>
        <location filename="../peers_discovery_dialog.py" line="55"/>
        <source>Discovering peers ...</source>
        <translation type="obsolete">Descobrint peers ...</translation>
    </message>
    <message>
        <location filename="../synchronizer.py" line="64"/>
        <source>Your IP is:</source>
        <translation type="obsolete">La teva IP es:</translation>
    </message>
</context>
</TS>
